// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pepoiixljdbhczuqwatm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcG9paXhsamRiaGN6dXF3YXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MzY1NDYsImV4cCI6MjA1NjAxMjU0Nn0.SX5WKexW63EvoJ2JuCRt4S0lLJ_Js2byp9PEqIjpgdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);